/* ============================================================
   WISAMIN — ข้อมูลสินค้ากลาง (แหล่งข้อมูลเดียวของทั้งเว็บ)
   ------------------------------------------------------------
   ข้อมูลจริงจากสินค้าตราวิษามิน (WISAMIN Brand) ที่จำหน่ายจริง
   ผ่าน max-globalshop.com — ชื่อ/ราคา/รูป/เลข อย. อ้างอิงของจริง
   ข้อความการตลาดเขียนใหม่ในกรอบ อย. (อาหารเสริม):
   ขายไลฟ์สไตล์/โภชนาการ ไม่อ้างรักษา/ป้องกัน/ลดน้ำหนัก
   ============================================================ */

window.WISAMIN_PRODUCTS = [
  {
    id: 'protein-plant',
    name: 'WISAMIN Protein Plant สูตร 4',
    subtitle: 'โปรตีนจากพืช 5 ชนิด ออร์แกนิก มี 14 รสชาติ',
    category: 'protein', categoryLabel: 'โปรตีน',
    badge: 'ขายดี',
    price: 69, oldPrice: 120, unit: '/ ซอง 50 กรัม (คละรสได้)',
    rating: 4.8, reviews: 2140, stock: 58, color: '#7a8b5a',
    image: 'assets/products/protein-plant.jpg',
    short: 'โปรตีนจากพืชออร์แกนิก ปราศจาก GMO และกลูเตน เสริมโพรไบโอติก 6 สายพันธุ์ ชงดื่มง่าย',
    highlights: [
      'โปรตีนจากพืช 5 ชนิด ออร์แกนิก ไม่ใช้ GMO',
      'ปลอดกลูเตน เสริมโพรไบโอติก 6 สายพันธุ์',
      'เลือกได้ 14 รสชาติ ชงดื่มสะดวก',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'โปรตีนจากพืชผสม 5 ชนิด, โพรไบโอติก 6 สายพันธุ์',
    directions: 'ผสม 1 ซอง (50 กรัม) กับน้ำเปล่าหรือน้ำเย็น 200-250 มล. ชงดื่มได้ทุกวัน',
    fda: '10-1-05061-5-0181',
  },
  {
    id: 'clear-protein-plant',
    name: 'WISAMIN Clear Protein Plant สูตร 5',
    subtitle: 'โปรตีนพืชจากถั่วลันเตา เปปไทด์ ชนิดใส มี 5 รสชาติ',
    category: 'protein', categoryLabel: 'โปรตีน',
    badge: null,
    price: 79, oldPrice: 159, unit: '/ ซอง 45 กรัม',
    rating: 4.7, reviews: 860, stock: 44, color: '#8a9b6a',
    image: 'assets/products/clear-protein-plant.jpg',
    short: 'โปรตีนพืชสูตรน้ำใส ดื่มง่ายไม่ข้น เหมาะกับคนที่ไม่ชอบโปรตีนแบบเข้มข้น',
    highlights: [
      'โปรตีนจากถั่วลันเตา เปปไทด์',
      'เนื้อสัมผัสใส ดื่มง่าย ไม่ข้นเลี่ยน',
      'มี 5 รสชาติให้เลือก',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'โปรตีนจากถั่วลันเตา เปปไทด์',
    directions: 'ผสม 1 ซอง (45 กรัม) กับน้ำเย็น 250-300 มล. คนให้เข้ากันแล้วดื่ม',
    fda: '10-1-05061-5-0221',
  },
  {
    id: 'egg-white-protein',
    name: 'WISAMIN Egg White Protein',
    subtitle: 'โปรตีนไข่ขาว รสโกโก้ นำเข้าวัตถุดิบจากอิตาลี',
    category: 'protein', categoryLabel: 'โปรตีน',
    badge: null,
    price: 69, oldPrice: 129, unit: '/ ซอง 45 กรัม',
    rating: 4.8, reviews: 690, stock: 51, color: '#6b4f3a',
    image: 'assets/products/egg-white-protein.jpg',
    short: 'โปรตีนจากไข่ขาวคุณภาพสูง เสริมวิตามินและแร่ธาตุ เหมาะกับคนออกกำลังกาย',
    highlights: [
      'โปรตีนจากไข่ขาว นำเข้าวัตถุดิบจากอิตาลี',
      'เสริมวิตามินและแร่ธาตุรวม',
      'มีกรดอะมิโนที่จำเป็นครบถ้วน',
      'ไม่มีไขมันจากนม เหมาะกับคนคุมอาหาร',
    ],
    ingredients: 'โปรตีนไข่ขาว, ผงโกโก้, วิตามินและแร่ธาตุรวม',
    directions: 'ผสม 1 ซอง (45 กรัม) กับน้ำเย็น 200-250 มล. ดื่มระหว่างวันหรือหลังออกกำลังกาย',
    fda: '10-1-05061-5-0252',
  },
  {
    id: 'chicken-protein',
    name: 'WISAMIN Chicken Protein',
    subtitle: 'โปรตีนจากอกไก่ ไฮโดรไลซ์ มี 4 รสชาติ',
    category: 'protein', categoryLabel: 'โปรตีน',
    badge: null,
    price: 69, oldPrice: 129, unit: '/ ซอง 45 กรัม',
    rating: 4.7, reviews: 410, stock: 36, color: '#a9713f',
    image: 'assets/products/chicken-protein.jpg',
    short: 'โปรตีนจากอกไก่แท้เกรดไฮโดรไลซ์ ปลอดกลูเตนและ GMO เหมาะกับสายรักสุขภาพ',
    highlights: [
      'โปรตีนจากอกไก่แท้ เกรดไฮโดรไลซ์',
      'ปลอดกลูเตน ปลอด GMO',
      'มี 4 รสชาติให้เลือก',
      'พกพาสะดวก ชงดื่มง่าย',
    ],
    ingredients: 'โปรตีนจากอกไก่ (Hydrolyzed Chicken Protein)',
    directions: 'ผสม 1 ซอง (45 กรัม) กับน้ำเย็น 200-250 มล. ดื่มระหว่างวัน',
  },
  {
    id: 'pea-protein-isolate',
    name: 'WISAMIN Pea Protein Isolate',
    subtitle: 'โปรตีนจากถั่วลันเตา 100% ออร์แกนิก',
    category: 'protein', categoryLabel: 'โปรตีน',
    badge: null,
    price: 79, oldPrice: 159, unit: '/ ถุง 100 กรัม',
    rating: 4.8, reviews: 520, stock: 33, color: '#5e6b45',
    image: 'assets/products/pea-protein-isolate.jpg',
    short: 'โปรตีนจากพืชสูตรไอโซเลท เข้มข้น ออร์แกนิก ปลอด GMO เหมาะกับสายวีแกน',
    highlights: [
      'โปรตีนจากถั่วลันเตา 100%',
      'ออร์แกนิก ปลอด GMO',
      'เหมาะกับสายมังสวิรัติ/วีแกน',
      'ไม่มีแลคโตส ย่อยง่าย',
    ],
    ingredients: 'โปรตีนจากถั่วลันเตาไอโซเลท ออร์แกนิก 100%',
    directions: 'ผสม 2 ช้อนตวง กับน้ำหรือนมพืช 250 มล. ดื่มเป็นมื้อเสริมได้ทุกวัน',
    fda: '10-1-05061-5-0100',
  },
  {
    id: 'organic-rice-protein',
    name: 'WISAMIN Organic Rice Protein',
    subtitle: 'เครื่องดื่มโปรตีนจากข้าว ออร์แกนิก 100%',
    category: 'protein', categoryLabel: 'โปรตีน',
    badge: null,
    price: 79, oldPrice: 149, unit: '/ ถุง 100 กรัม',
    rating: 4.7, reviews: 300, stock: 28, color: '#c9a876',
    image: 'assets/products/organic-rice-protein.jpg',
    short: 'โปรตีนจากข้าวออร์แกนิก ทางเลือกสำหรับคนแพ้โปรตีนจากนมและถั่วเหลือง',
    highlights: [
      'สกัดจากข้าวออร์แกนิก 100%',
      'ปลอด GMO',
      'ทางเลือกสำหรับคนแพ้นม/ถั่วเหลือง',
      'ย่อยง่าย ดื่มสบายท้อง',
    ],
    ingredients: 'โปรตีนจากข้าวออร์แกนิก 100%',
    directions: 'ผสม 2 ช้อนตวง กับน้ำเย็น 200-250 มล. ดื่มระหว่างวัน',
    fda: '10-1-05061-5-0107',
  },

  {
    id: 'gluta-colla-blink',
    name: 'WISAMIN Gluta Colla Blink',
    subtitle: 'กลูต้าคอลลาเจนชงดื่ม รสโกโก้ (มี 5 รสชาติ)',
    category: 'collagen', categoryLabel: 'คอลลาเจน',
    badge: 'ขายดี',
    price: 69, oldPrice: 99, unit: '/ ซอง 28 กรัม',
    rating: 4.9, reviews: 3380, stock: 60, color: '#8a5a6e',
    image: 'assets/products/gluta-colla-blink.jpg',
    short: 'เครื่องดื่มผสมคอลลาเจนไดเปปไทด์จากปลาและกลูต้าไธโอน สำหรับคนที่อยากดูแลผิวจากภายใน',
    highlights: [
      'คอลลาเจนไดเปปไทด์จากปลา 10,000 มก.',
      'เสริมกลูต้าไธโอนและ MCT Oil',
      'เลือกได้ 5 รสชาติ',
      'ชงง่าย พกพาสะดวก',
    ],
    ingredients: 'คอลลาเจนเปปไทด์จากปลา 10,000 มก., ผงโกโก้, MCT Oil, กลูต้าไธโอน',
    directions: 'ผสม 1 ซอง (28 กรัม) กับน้ำ 200-300 มล. คนให้เข้ากันแล้วดื่มทันที',
    fda: '10-1-05061-5-0212',
  },
  {
    id: 'colla-max-plus',
    name: 'WISAMIN Colla-Max Plus+',
    subtitle: 'เพียวคอลลาเจน 100% ไทป์ II ไดเปปไทด์',
    category: 'collagen', categoryLabel: 'คอลลาเจน',
    badge: null,
    price: 129, oldPrice: 390, unit: '/ กระปุก 50 กรัม',
    rating: 4.8, reviews: 940, stock: 27, color: '#9c5a8a',
    image: 'assets/products/colla-max-plus.jpg',
    short: 'คอลลาเจนเปปไทด์เข้มข้น ไม่ปรุงแต่งรส ผสมกับเครื่องดื่มโปรดได้ตามใจชอบ',
    highlights: [
      'เพียวคอลลาเจน 100% ไม่ปรุงแต่ง',
      'ไทป์ II ไดเปปไทด์ ดูดซึมง่าย',
      'ผสมกับเครื่องดื่มโปรดได้ทุกชนิด',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'คอลลาเจนเปปไทด์ ไทป์ II ไดเปปไทด์ 100%',
    directions: 'ตักผสมกับเครื่องดื่มที่ชื่นชอบ วันละ 1 ครั้ง',
    fda: '10-1-05061-5-0075',
  },
  {
    id: 'elastin-collagen-peptide',
    name: 'WISAMIN Elastin Collagen Peptide',
    subtitle: 'อีลาสตินคอลลาเจนเปปไทด์ จากปลาโบนิโต',
    category: 'collagen', categoryLabel: 'คอลลาเจน',
    badge: null,
    price: 295, oldPrice: 590, unit: '/ กล่อง 15 ซอง',
    rating: 4.8, reviews: 210, stock: 18, color: '#c15b78',
    image: 'assets/products/elastin-collagen-peptide.jpg',
    short: 'คอลลาเจนเปปไทด์เสริมอีลาสติน สำหรับคนที่อยากดูแลผิวให้ดูยืดหยุ่นจากภายใน',
    highlights: [
      'อีลาสตินจากปลาโบนิโต',
      'คอลลาเจนเปปไทด์คุณภาพสูง',
      'บรรจุแบบซองพกพาสะดวก 15 ซอง',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'อีลาสตินจากปลาโบนิโต (Bonito Elastin Peptide), คอลลาเจนเปปไทด์',
    directions: 'ผสม 1 ซองกับน้ำ 150-200 มล. ดื่มวันละ 1 ครั้ง',
    fda: '10-1-05061-5-0251',
  },
  {
    id: 'colla-uc-ll-type-ll',
    name: 'WISAMIN Colla UC-II Type II',
    subtitle: 'คอลลาเจนยูซี-ทู ไทป์ II ชนิดแคปซูล',
    category: 'collagen', categoryLabel: 'คอลลาเจน',
    badge: null,
    price: 295, oldPrice: 490, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.7, reviews: 160, stock: 15, color: '#8a5a9e',
    image: 'assets/products/colla-uc-ll-type-ll.jpg',
    short: 'คอลลาเจนยูซี-ทูแบบแคปซูล ทานง่าย ไม่ต้องชง เหมาะกับคนไม่สะดวกพกผง',
    highlights: [
      'คอลลาเจน UC-II Type II เข้มข้น',
      'แคปซูลทานง่าย พกพาสะดวก',
      'ไม่ต้องชงหรือผสมน้ำ',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'คอลลาเจน UC-II Type II',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0229',
  },

  {
    id: 'active-c',
    name: 'WISAMIN Active C',
    subtitle: 'วิตามินซีแคปซูล สกัดจากธรรมชาติ',
    category: 'vitamin', categoryLabel: 'วิตามิน',
    badge: 'ขายดี',
    price: 85, oldPrice: 159, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.9, reviews: 1870, stock: 49, color: '#f0803c',
    image: 'assets/products/active-c.jpg',
    short: 'วิตามินซีสกัดจากอเซโรล่าเชอร์รี่และเมล็ดองุ่น สำหรับคนที่อยากดูแลตัวเองทุกวัน',
    highlights: [
      'สกัดจากอเซโรล่าเชอร์รี่ธรรมชาติ',
      'เสริมสารสกัดจากเมล็ดองุ่น',
      'ทานง่ายวันละ 1 แคปซูล',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'สารสกัดอเซโรล่าเชอร์รี่, สารสกัดเมล็ดองุ่น, แคลเซียม แอสคอร์เบต',
    directions: 'รับประทานวันละ 1 แคปซูล พร้อมอาหาร',
    fda: '10-1-05061-5-0039',
  },
  {
    id: 'zinc-amino-acid',
    name: 'WISAMIN Zinc Amino Acid Chelate Plus',
    subtitle: 'ซิงค์อะมิโนแอซิด คีเลต 590 มก.',
    category: 'vitamin', categoryLabel: 'วิตามิน',
    badge: null,
    price: 159, oldPrice: 390, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.7, reviews: 240, stock: 22, color: '#e0a63c',
    image: 'assets/products/zinc-amino-acid.jpg',
    short: 'แร่ธาตุสังกะสีในรูปแบบคีเลตที่ร่างกายดูดซึมง่าย เหมาะกับการดูแลสุขภาพประจำวัน',
    highlights: [
      'สังกะสีรูปแบบคีเลต ดูดซึมง่าย',
      'ความเข้มข้น 590 มก./แคปซูล',
      'ทานง่ายวันละ 1 แคปซูล',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'ซิงค์อะมิโนแอซิด คีเลต 590 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล พร้อมอาหาร',
    fda: '10-1-05061-5-0187',
  },

  {
    id: 'pea-fiber',
    name: 'WISAMIN Pea Fiber',
    subtitle: 'ใยอาหารจากถั่วลันเตา ชนิดผง',
    category: 'fiber', categoryLabel: 'ไฟเบอร์',
    badge: 'ขายดี',
    price: 59, oldPrice: 129, unit: '/ ถุง 100 กรัม',
    rating: 4.8, reviews: 1560, stock: 55, color: '#5e6b45',
    image: 'assets/products/pea-fiber.jpg',
    short: 'ใยอาหารจากถั่วลันเตา 100% ไม่มีน้ำตาล ไม่มีไขมัน เหมาะกับคนที่คุมมื้ออาหาร',
    highlights: [
      'ใยอาหาร 7 กรัม ต่อหน่วยบริโภค',
      'ไม่มีน้ำตาล ไม่มีไขมัน สูตรวีแกน',
      'ปลอดกลูเตน ไม่ใช้ทรานส์แฟต',
      'ชงง่าย ละลายไว',
    ],
    ingredients: 'ใยอาหารจากถั่วลันเตา (Pea Fiber) 100%',
    directions: 'ผสม 2 ช้อนตวง (10 กรัม) กับน้ำ 200 มล. ดื่มวันละ 1-2 ครั้ง',
    fda: '10-1-05061-5-0235',
  },
  {
    id: 'psyllium-husk',
    name: 'WISAMIN Psyllium Husk',
    subtitle: 'ผงไซเลียมฮัสก์ ใยอาหารธรรมชาติ',
    category: 'fiber', categoryLabel: 'ไฟเบอร์',
    badge: null,
    price: 89, oldPrice: 169, unit: '/ ถุง 50 กรัม',
    rating: 4.7, reviews: 380, stock: 30, color: '#7c8a5f',
    image: 'assets/products/psyllium-husk.jpg',
    short: 'ใยอาหารจากเปลือกเมล็ดไซเลียม ทางเลือกสำหรับคนที่อยากเสริมใยอาหารในแต่ละวัน',
    highlights: [
      'ใยอาหารจากธรรมชาติ 100%',
      'ไม่มีน้ำตาล',
      'ชงง่าย ละลายในน้ำได้ดี',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'ผงไซเลียมฮัสก์ (Psyllium Husk) 100%',
    directions: 'ผสม 1-2 ช้อนตวง กับน้ำเปล่า 200 มล. ดื่มทันทีหลังผสม',
    fda: '10-1-05061-5-0190',
  },
  {
    id: 'fiber-plus-mct',
    name: 'WISAMIN Fiber Plus MCT',
    subtitle: 'ใยอาหารเสริม MCT ชนิดผง',
    category: 'fiber', categoryLabel: 'ไฟเบอร์',
    badge: null,
    price: 99, oldPrice: 129, unit: '/ ถุง 100 กรัม',
    rating: 4.6, reviews: 190, stock: 26, color: '#4f8a6b',
    image: 'assets/products/fiber-plus-mct.jpg',
    short: 'ใยอาหารผสม MCT ครีม สูตรเข้มข้น เหมาะกับคนที่ต้องการเสริมใยอาหารพร้อมความเข้มข้น',
    highlights: [
      'ผสมใยอาหารและ MCT ครีม',
      'ชงง่าย ละลายไว',
      'ไม่มีน้ำตาลทราย',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'ใยอาหาร, MCT ครีม',
    directions: 'ผสม 2 ช้อนตวง กับน้ำเปล่า 200 มล. ดื่มวันละ 1-2 ครั้ง',
    fda: '10-1-05061-5-0231',
  },

  {
    id: 'finger-cap',
    name: 'WISAMIN Finger Cap',
    subtitle: 'สารสกัดกระชายขาวผสมมะขามป้อม',
    category: 'herbal', categoryLabel: 'สมุนไพรสกัด',
    badge: null,
    price: 85, oldPrice: 159, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.6, reviews: 310, stock: 25, color: '#a0785a',
    image: 'assets/products/finger-cap.jpg',
    short: 'สารสกัดจากกระชายขาวและมะขามป้อม บรรจุแคปซูลจากพืช ทานง่ายวันละ 1 เม็ด',
    highlights: [
      'สารสกัดกระชายขาว 240 มก.',
      'ผงมะขามป้อม 260 มก.',
      'แคปซูลจากพืช (Vegetable Capsule)',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'สารสกัดกระชายขาว 240 มก., ผงมะขามป้อม 260 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0084',
  },
  {
    id: 'white-kidney-bean',
    name: 'WISAMIN White Kidney Bean Extract',
    subtitle: 'สารสกัดจากถั่วขาว 100% ชนิดแคปซูล',
    category: 'herbal', categoryLabel: 'สมุนไพรสกัด',
    badge: null,
    price: 169, oldPrice: 359, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.6, reviews: 480, stock: 34, color: '#8a6b4f',
    image: 'assets/products/white-kidney-bean.jpg',
    short: 'สารสกัดจากถั่วขาวธรรมชาติ ปลอดกลูเตนและ GMO ทางเลือกสำหรับคนที่คุมมื้ออาหารแป้ง',
    highlights: [
      'สกัดจากถั่วขาวธรรมชาติ 500 มก.',
      'ปลอดกลูเตน ไม่ใช้ GMO',
      'แคปซูลทานง่ายวันละ 1 เม็ด',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'สารสกัดจากถั่วขาว (White Kidney Bean Extract) 500 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0179',
  },
  {
    id: 'cactus-extract',
    name: 'WISAMIN Cactus Extract',
    subtitle: 'สารสกัดกระบองเพชร ชนิดแคปซูล วีแกน',
    category: 'herbal', categoryLabel: 'สมุนไพรสกัด',
    badge: null,
    price: 159, oldPrice: 289, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.5, reviews: 220, stock: 20, color: '#7a9e6b',
    image: 'assets/products/cactus-extract.jpg',
    short: 'สารสกัดจากกระบองเพชรธรรมชาติ แคปซูลสูตรวีแกน เหมาะกับไลฟ์สไตล์คนที่ดูแลตัวเอง',
    highlights: [
      'สกัดจากกระบองเพชร 500 มก.',
      'สูตรวีแกน (VEGAN)',
      'ทานง่ายวันละ 1 แคปซูล',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'สารสกัดกระบองเพชร (Cactus Extract) 500 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0165',
  },
  {
    id: 'gotu-kola-extract-plus',
    name: 'WISAMIN Gotu Kola Extract Plus',
    subtitle: 'สารสกัดจากใบบัวบก ชนิดแคปซูล',
    category: 'herbal', categoryLabel: 'สมุนไพรสกัด',
    badge: null,
    price: 169, oldPrice: 359, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.6, reviews: 150, stock: 19, color: '#6b8a5a',
    image: 'assets/products/gotu-kola-extract-plus.jpg',
    short: 'สารสกัดจากใบบัวบกธรรมชาติ ผลิตภัณฑ์เสริมอาหารสำหรับคนที่ใส่ใจดูแลตัวเอง',
    highlights: [
      'สกัดจากใบบัวบกธรรมชาติ',
      'แคปซูลทานง่าย',
      'ผ่านมาตรฐาน GMP',
      'ขึ้นทะเบียน อย.',
    ],
    ingredients: 'สารสกัดจากใบบัวบก (Gotu Kola Extract)',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0237',
  },
  {
    id: 'l-carnitine-100',
    name: 'WISAMIN L-Carnitine 100%',
    subtitle: 'แอล-คาร์นิทีน 500 มก./แคปซูล',
    category: 'herbal', categoryLabel: 'เสริมออกกำลังกาย',
    badge: null,
    price: 195, oldPrice: 390, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.6, reviews: 210, stock: 17, color: '#3c7fb0',
    image: 'assets/products/l-carnitine-100.jpg',
    short: 'กรดอะมิโนแอล-คาร์นิทีนเข้มข้น เหมาะกับคนออกกำลังกายที่ต้องการสารอาหารเฉพาะทาง',
    highlights: [
      'แอล-คาร์นิทีนเข้มข้น 500 มก.',
      'เหมาะกับคนออกกำลังกาย',
      'แคปซูลทานง่าย',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'แอล-คาร์นิทีน (L-Carnitine) 500 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0123',
  },

  {
    id: 'l-glutamine-100',
    name: 'WISAMIN L-Glutamine 100%',
    subtitle: 'แอล-กลูตามีน 1,110 มก./แคปซูล',
    category: 'sports', categoryLabel: 'เสริมออกกำลังกาย',
    badge: null,
    price: 195, oldPrice: 390, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.7, reviews: 260, stock: 21, color: '#35618a',
    image: 'assets/products/l-glutamine-100.jpg',
    short: 'กรดอะมิโนที่พบมากที่สุดในกล้ามเนื้อ เหมาะกับคนออกกำลังกายที่ต้องการฟื้นตัวหลังเทรน',
    highlights: [
      'แอล-กลูตามีนเข้มข้น 1,110 มก.',
      'เป็นส่วนประกอบหลักของเซลล์กล้ามเนื้อ',
      'เหมาะกับนักออกกำลังกาย',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'แอล-กลูตามีน (L-Glutamine) 1,110 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0124',
  },
  {
    id: 'l-arginine',
    name: 'WISAMIN L-Arginine 100%',
    subtitle: 'แอล-อาร์จีนีน 1,110 มก./แคปซูล',
    category: 'sports', categoryLabel: 'เสริมออกกำลังกาย',
    badge: null,
    price: 195, oldPrice: 390, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.6, reviews: 170, stock: 16, color: '#4a6b8a',
    image: 'assets/products/l-arginine.jpg',
    short: 'กรดอะมิโนแอล-อาร์จีนีนเข้มข้น เหมาะกับคนออกกำลังกายที่ต้องการสารอาหารเฉพาะทาง',
    highlights: [
      'แอล-อาร์จีนีนเข้มข้น 1,110 มก.',
      'เหมาะกับนักออกกำลังกาย',
      'แคปซูลทานง่าย',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'แอล-อาร์จีนีน (L-Arginine) 1,110 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0122',
  },
  {
    id: 'creatine-monohydrate',
    name: 'WISAMIN Creatine Monohydrate',
    subtitle: 'ครีเอทีน โมโนไฮเดรต 100%',
    category: 'sports', categoryLabel: 'เสริมออกกำลังกาย',
    badge: null,
    price: 195, oldPrice: 390, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.8, reviews: 340, stock: 24, color: '#5a7ba0',
    image: 'assets/products/creatine-monohydrate.jpg',
    short: 'ครีเอทีนโมโนไฮเดรตบริสุทธิ์ สำหรับผู้ที่รักการออกกำลังกาย',
    highlights: [
      'ครีเอทีนโมโนไฮเดรต 100% บริสุทธิ์',
      'เหมาะกับผู้รักการออกกำลังกาย',
      'แคปซูลทานง่าย ไม่ต้องชง',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'ครีเอทีน โมโนไฮเดรต (Creatine Monohydrate) 100%',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0125',
  },
  {
    id: 'l-phenylalanine',
    name: 'WISAMIN L-Phenylalanine',
    subtitle: 'แอล-ฟีนิลอลานีน 500 มก. วีแกน',
    category: 'sports', categoryLabel: 'เสริมออกกำลังกาย',
    badge: null,
    price: 159, oldPrice: 289, unit: '/ กระปุก 30 แคปซูล',
    rating: 4.5, reviews: 120, stock: 14, color: '#3c7fb0',
    image: 'assets/products/l-phenylalanine.jpg',
    short: 'กรดอะมิโนจำเป็นชนิดวีแกน แคปซูลทานง่ายสำหรับเสริมสารอาหารประจำวัน',
    highlights: [
      'แอล-ฟีนิลอลานีนเข้มข้น 500 มก.',
      'สูตรวีแกน (VEGAN)',
      'แคปซูลทานง่าย',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'แอล-ฟีนิลอลานีน (L-Phenylalanine) 500 มก.',
    directions: 'รับประทานวันละ 1 แคปซูล',
    fda: '10-1-05061-5-0164',
  },

  {
    id: 'mct-oil-powder',
    name: 'WISAMIN MCT Oil Powder',
    subtitle: 'น้ำมัน MCT ชนิดผง ชงดื่มง่าย',
    category: 'drink', categoryLabel: 'เครื่องดื่ม',
    badge: null,
    price: 149, oldPrice: 189, unit: '/ ถุง 100 กรัม',
    rating: 4.6, reviews: 190, stock: 23, color: '#d9c08a',
    image: 'assets/products/mct-oil-powder.jpg',
    short: 'น้ำมัน MCT แปรรูปเป็นผง ชงง่ายกว่าน้ำมันเหลว เหมาะกับคนที่ชื่นชอบสูตรคีโต',
    highlights: [
      'แปรรูปจากน้ำมัน MCT คุณภาพสูง',
      'ชงง่ายกว่ารูปแบบน้ำมันเหลว',
      'เหมาะกับไลฟ์สไตล์คีโต',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'น้ำมัน MCT ชนิดผง (MCT Oil Powder)',
    directions: 'ผสม 1-2 ช้อนตวง กับเครื่องดื่มร้อนหรือเย็น',
    fda: '10-1-05061-5-0192',
  },
  {
    id: 'almond-milk-powder',
    name: 'WISAMIN Almond Milk Powder',
    subtitle: 'เครื่องดื่มผงนมอัลมอนด์ 100%',
    category: 'drink', categoryLabel: 'เครื่องดื่ม',
    badge: null,
    price: 139, oldPrice: 189, unit: '/ ถุง 100 กรัม',
    rating: 4.7, reviews: 230, stock: 27, color: '#e8dcc0',
    image: 'assets/products/almond-milk-powder.jpg',
    short: 'นมอัลมอนด์ชนิดผง ชงดื่มง่าย ทางเลือกสำหรับคนที่หลีกเลี่ยงนมวัว',
    highlights: [
      'ทำจากอัลมอนด์ 100%',
      'ชงง่าย ละลายไว',
      'ทางเลือกสำหรับคนแพ้นมวัว',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'ผงนมอัลมอนด์ (Almond Milk Powder) 100%',
    directions: 'ผสม 2 ช้อนตวง กับน้ำอุ่นหรือน้ำเย็น 200 มล.',
    fda: '10-1-05061-5-0194',
  },
  {
    id: 'purple-sweet-potato',
    name: 'WISAMIN Purple Sweet Potato Powder',
    subtitle: 'ผงมันเทศหวานสีม่วงโอกินาว่า ออร์แกนิก',
    category: 'drink', categoryLabel: 'เครื่องดื่ม',
    badge: null,
    price: 99, oldPrice: 159, unit: '/ ถุง 100 กรัม',
    rating: 4.6, reviews: 140, stock: 19, color: '#8a5a9e',
    image: 'assets/products/purple-sweet-potato.jpg',
    short: 'ผงมันเทศหวานสีม่วงออร์แกนิก ชงดื่มง่าย รสชาติหอมหวานตามธรรมชาติ',
    highlights: [
      'มันเทศหวานสีม่วงโอกินาว่าออร์แกนิก 100%',
      'ไม่ปรุงแต่งเพิ่ม',
      'ชงง่าย ละลายไว',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'ผงมันเทศหวานสีม่วงโอกินาว่าออร์แกนิก 100%',
    directions: 'ผสม 2 ช้อนตวง กับน้ำอุ่นหรือน้ำเย็น 200 มล.',
    fda: '10-1-05061-5-0116',
  },

  {
    id: 'rbika-black-coffee',
    name: 'WISAMIN Rbika Black Coffee',
    subtitle: 'กาแฟอาราบิก้าแท้ 100% ชนิดซอง',
    category: 'coffee', categoryLabel: 'กาแฟ',
    badge: null,
    price: 249, oldPrice: 490, unit: '/ กล่อง 30 ซอง',
    rating: 4.7, reviews: 260, stock: 32, color: '#4a3728',
    image: 'assets/products/rbika-black-coffee.jpg',
    short: 'กาแฟดำสำเร็จรูปจากอาราบิก้าแท้ ชงง่าย พกพาสะดวก สำหรับคนที่ชื่นชอบกาแฟดำ',
    highlights: [
      'อาราบิก้าแท้ 100%',
      'ชนิดซองสำเร็จรูป พกพาง่าย',
      'ไม่ผสมครีมเทียม',
      'บรรจุ 30 ซอง/กล่อง',
    ],
    ingredients: 'กาแฟอาราบิก้าแท้ 100%',
    directions: 'ชงกับน้ำร้อน 150-200 มล. คนให้ละลาย ดื่มได้ทันที',
  },
  {
    id: 'cordy-coffee',
    name: 'WISAMIN Cordy Coffee',
    subtitle: 'กาแฟผสมถั่งเช่า โสม เห็ดหลินจือ',
    category: 'coffee', categoryLabel: 'กาแฟ',
    badge: null,
    price: 249, oldPrice: 390, unit: '/ กล่อง ชนิดผง',
    rating: 4.6, reviews: 180, stock: 22, color: '#5a3c26',
    image: 'assets/products/cordy-coffee.jpg',
    short: 'กาแฟปรุงสำเร็จผสมสมุนไพรถั่งเช่า โสม และเห็ดหลินจือ สำหรับคนที่ชอบดื่มกาแฟไปพร้อมไลฟ์สไตล์ใส่ใจสุขภาพ',
    highlights: [
      'ผสมถั่งเช่า โสม เห็ดหลินจือและสมุนไพร',
      'ชงง่าย ละลายไว',
      'รสชาติกลมกล่อม',
      'ผ่านมาตรฐาน GMP ขึ้นทะเบียน อย.',
    ],
    ingredients: 'กาแฟปรุงสำเร็จผสมถั่งเช่า โสม เห็ดหลินจือและสมุนไพร',
    directions: 'ชงกับน้ำร้อน 150-200 มล. คนให้ละลาย ดื่มได้ทันที',
    fda: '10-1-05061-5-0022',
  },

  {
    id: 'luohanguo-sweetener',
    name: 'WISAMIN Luohanguo 2%',
    subtitle: 'น้ำตาลหล่อฮั่งก้วยออร์แกนิก ไม่มีแคลอรี่',
    category: 'sweetener', categoryLabel: 'น้ำตาลเพื่อสุขภาพ',
    badge: null,
    price: 129, oldPrice: 259, unit: '/ กล่อง 30 ซอง',
    rating: 4.7, reviews: 210, stock: 29, color: '#a9c98a',
    image: 'assets/products/luohanguo-sweetener.jpg',
    short: 'สารให้ความหวานจากผลหล่อฮั่งก้วยออร์แกนิก ไม่มีน้ำตาล ไม่มีแคลอรี่ เหมาะกับคนคุมอาหาร',
    highlights: [
      'สกัดจากหล่อฮั่งก้วยออร์แกนิก 2%',
      'ไม่มีน้ำตาล ไม่มีแคลอรี่',
      'ดัชนีน้ำตาลเป็นศูนย์ เหมาะกับสายคีโต',
      'หวานกว่าน้ำตาลทั่วไป ไม่มีรสขม',
    ],
    ingredients: 'สารสกัดหล่อฮั่งก้วยออร์แกนิก (Organic Monk Fruit Extract) 2%',
    directions: 'ใช้แทนน้ำตาลในเครื่องดื่มหรืออาหารตามชอบ',
    fda: '10-3-34463-5-0017',
  },

  {
    id: 'wisamin-shake-the-cup',
    name: 'WISAMIN Shake The Cup',
    subtitle: 'แก้วเชคโปรตีน สแตนเลส 304 ขนาด 700 มล.',
    category: 'accessory', categoryLabel: 'อุปกรณ์',
    badge: null,
    price: 590, oldPrice: 990, unit: '/ ชิ้น',
    rating: 4.8, reviews: 95, stock: 40, color: '#7a8a99',
    image: 'assets/products/wisamin-shake-the-cup.jpg',
    short: 'แก้วเชคสแตนเลสเกรดอาหาร ปลอด BPA เหมาะสำหรับพกเชคโปรตีนหรือเครื่องดื่มเสริมอาหารทุกชนิด',
    highlights: [
      'สแตนเลส 304 เกรดอาหาร',
      'ปลอดสาร BPA',
      'ความจุ 700 มล.',
      'ใช้เชคได้ทั้งโปรตีนและเครื่องดื่มเสริมอาหาร',
    ],
    ingredients: '—',
    directions: 'ใส่ผงและน้ำตามสัดส่วนที่แนะนำ ปิดฝาแล้วเขย่าให้เข้ากัน',
  },
];

/* ---- เซ็ตสุดคุ้ม (บันเดิล) ---- */
window.WISAMIN_BUNDLE = {
  id: 'daily-essentials',
  name: 'เซ็ต Daily Essentials',
  subtitle: 'ดูแลตัวเองครบ จบในเซ็ตเดียว',
  items: ['active-c', 'pea-fiber', 'gluta-colla-blink'],
  bundlePrice: 159,
  savePercent: 25,
};

/* ---- หมวดหมู่สินค้า (ใช้ทำฟิลเตอร์หน้า shop) ---- */
window.WISAMIN_CATEGORIES = [
  { key: 'all', label: 'ทั้งหมด' },
  { key: 'protein', label: 'โปรตีน' },
  { key: 'collagen', label: 'คอลลาเจน' },
  { key: 'vitamin', label: 'วิตามิน' },
  { key: 'fiber', label: 'ไฟเบอร์' },
  { key: 'herbal', label: 'สมุนไพรสกัด' },
  { key: 'sports', label: 'เสริมออกกำลังกาย' },
  { key: 'drink', label: 'เครื่องดื่ม' },
  { key: 'coffee', label: 'กาแฟ' },
  { key: 'sweetener', label: 'น้ำตาลเพื่อสุขภาพ' },
  { key: 'accessory', label: 'อุปกรณ์' },
];

/* ---- helper ค้นหาสินค้า ---- */
window.getProductById = function (id) {
  return (window.WISAMIN_PRODUCTS || []).find(function (p) { return p.id === id; });
};
